version: 2

models:
  - name: fct_sales
    columns:
      - name: reference_id
        tests:
          - unique
          - not_null
      - name: order_date_kyiv
        tests:
          - not_null